name: 3D Contribution Calendar

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & push
        run: |
          git add -f profile-3d-contrib
          git commit -m "Generate 3D contribution calendar" || echo "no changes"
          git push origin main
